### PR TITLE
fix(MatchValidation): allow dot notation

### LINKED ISSUE #58: Cannot validation with sub props
Hi guy,

I cannot validate with AvField name: "Local.Password"

`<AvForm onValidSubmit={this.onSubmit}>
<FormGroup>
                        <Label for="Password" className="font-weight-bold">Mật khẩu</Label>
                        <AvGroup>
                            <AvField
                                type="password"
                                placeholder="Mật khẩu mới"
                                name="Local.Password"
                                onChange={this.onChange}
                                autoComplete="off"
                                validate={{
                                    required: {
                                        value: true,
                                        errorMessage: 'Bạn chưa điền mật khẩu !!!'
                                    },
                                    minLength: {
                                        value: '8',
                                        errorMessage: 'Mật khẩu ít nhất 8 ký tự !!!'
                                    },
                                    maxLength: {
                                        value: '25',
                                        errorMessage: 'Mật khẩu nhiều nhất 25 ký tự !!!'
                                    }
                                }}
                            />
                        </AvGroup>
                    </FormGroup>
                    <FormGroup>
                        <Label for="RePassword" className="font-weight-bold">Xác nhận mật khẩu</Label>
                        <AvGroup>
                            <AvField
                                type="password"
                                placeholder="Xác nhận mật khẩu mới"
                                name="RePassword"
                                autoComplete="off"
                                validate={{
                                    match: {
                                        value: 'Local.Password',
                                        errorMessage: 'Xác nhận mật khẩu không đúng !!!'
                                    }
                                }}
                            />
                        </AvGroup>
                    </FormGroup>
</AvForm>`

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Closes #58

### CODE REVIEW

File: src/AvValidator/match.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { isEmpty } from './utils';
+import get from 'lodash/get';
 
 export default function validate(value, context, constraint = {}) {
-  return isEmpty(value) || value === context[constraint.value] || constraint.errorMessage || false;
+  return isEmpty(value) || value === get(context, constraint.value) || constraint.errorMessage || false;
```
Comment (andrueandersoncs) [inline src/AvValidator/match.js]: is || false really necessary here? 
if anything in the chain evaluates to false it will return that regardless, right?
